<?php
/** @var \Magento\Newsletter\Block\Subscribe $block */
?>

<div class="block newsletter">
    <form class="form subscribe"
          novalidate
          action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
          method="post"
          id="newsletter-validate-detail">
        <div class="newsletter__row">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your mail')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button id="subscribe"
                        class="action subscribe newsletter secondary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe"
                        disabled>
                    <span><?= $block->escapeHtmlAttr(__('Subscribe')) ?></span>
                </button>
            </div>
        </div>

        <div class="field choice tos">
            <div id="tos-error" class="error-message"></div>
            <input name="tos" type="checkbox" id="tos" data-validate="{required:true}" data-msg-required="<?= __('You should accept the privacy policy') ?>" title="<?php echo __('I accept the legal terms and conditions'); ?>"/>
            <label class="label" for="tos">
                <span>
                    <?= __("I have read and accept the <a class='alink' href='%1'>General Purchase Conditions</a>, the <a class='alink' href='%2'>Privacy Policy</a>, and <a class='alink' href='%3'>Legal Notice.</a>", 'general-conditions', 'privacy-policy', 'legal-notice') ?>
                </span>
            </label>
        </div>
    </form>
</div>

<script type="text/javascript">
    require(["jquery"], function($) {
        $(document).ready(function() {
            $('#newsletter').on('keyup', function() {
                let empty = false;

                $('#newsletter').each(function() {
                    empty = $(this).val().length == 0;
                });

                if (empty)
                    $('#subscribe').attr('disabled', 'disabled');
                else
                    $('#subscribe').attr('disabled', false);
            });

            // Validate the tos checkbox and show error message if needed
            $('form').on('submit', function(event) {
                let tosChecked = $('#tos').is(':checked');
                if (!tosChecked) {
                    event.preventDefault();
                    $('#tos-error').text('<?= __('You should accept the privacy policy') ?>').show();
                } else {
                    $('#tos-error').hide();
                }
            });
        });
    });
</script>
