<?php
/**
 * @copyright Copyright (c) 2024 VASS
 * @author VASS Team
 */

/**
 * @var \Vass\ReviewSlider\Block\Widget\ReviewSlider $block
 * @var \Magento\Framework\Escaper $escaper
 */

$images = $block->getImages();
$texts = $block->getText();
$names = $block->getNames();
$stars = $block->getStars();
$urls = $block->getUrls();
$label = $block->getLabel();
$title = $block->getTitle();
$count = count($images);
$maxStars = 5;

?>
<div class="ba-review-slider__wrapper">
    <div class="ba-review-prev">
        <span class="icon icon-arrow-left"></span>
    </div>
    <div class="ba-review-slider swiper">
        <div class="swiper-wrapper">
            <?php for ($i = 0; $i < $count; $i++): ?>
                <?php if ($images[$i]): ?>
                    <div class="swiper-slide">
                        <div class="swiper-slide">
                            <div class="swiper-slide">
                                <span class="home-subtitle home-subtitle--outside">
                                    <?= /** @noEscape */ $title; ?>
                                </span>
                                <div class="ba-review__wrapper">
                                    <div class="ba-review-info-img">
                                        <img class="ba-review-img" src="<?= /** @noEscape */ $images[$i]; ?>" />
                                    </div>
                                    <div class="ba-review__rightcol">
                                         <span class="home-subtitle home-subtitle--inside">
                                            <?= /** @noEscape */ $title; ?>
                                        </span>
                                        <div class="ba-review-info">
                                            <div class="ba-review-label-star">
                                                <span class="ba-review-label">
                                                    <?= /** @noEscape */ $label[$i]; ?>
                                                </span>
                                                <span class="ba-review-star">
                                                    <?php for ($j = 0; $j < $stars[$i]; $j++): ?>
                                                        <span class="icon icon-full-start star-gold"></span>
                                                    <?php endfor; ?>
                                                    <?php for ($j = $stars[$i]; $j < $maxStars; $j++): ?>
                                                        <span class="icon icon-full-start star-grey"></span>
                                                    <?php endfor; ?>
                                                </span>
                                            </div>
                                                <span class="ba-review-title">
                                                    <?= /** @noEscape */ $texts[$i]; ?>
                                                </span>
                                                <span class="ba-review-name">
                                                    <?= /** @noEscape */ $names[$i]; ?>
                                                </span>
                                             </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
        <div class="swiper-scrollbar-review swiper-scrollbar-horizontal"></div>
    </div>
    <div class="ba-review-next">
        <span class="icon icon-arrow-right"></span>
    </div>
</div>

<?php $i = 0 ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Vass_SliderReview/js/review-slider": {}
        }
    }
</script>
