<?php
/**
 * @copyright Copyright (c) 2024 VASS
 * @author VASS Team
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
/** @var \Magento\Customer\ViewModel\LoginButton $loginButtonViewModel */
/** @var \Magento\Framework\Escaper $escaper */
$loginButtonViewModel = $block->getData('login_button_view_model');
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <div class="block-left">
            <img class="customer-login-image"
                src="<?= $escaper->escapeUrl($this->getViewFileUrl('Magento_Customer::image/customer_image.png')); ?>">
        </div>
        <div class="block-right">
            <div class="block-title">
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Personal information')) ?></strong>
            </div>
            <form class="form form-login"
                  action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset login" data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>">
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $escaper->escapeHtmlAttr($block->getUsername()) ?>"
                                <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                                   id="email" type="email" class="input-text"
                                   title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true, 'validate-email':true}"
                                   placeholder="<?= $escaper->escapeHtml(__('Email')) ?>">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                        <div class="control">
                            <input name="login[password]" type="password"
                                <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                                   class="input-text" id="pass"
                                   title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                                   data-validate="{required:true}"
                                   placeholder="<?= $escaper->escapeHtml(__('Password')) ?>">
                            <div class="field choice" data-bind="scope: 'showPassword'">
                                <icon class="icon icon-eye"></icon>
                                <!-- ko template: getTemplate() --><!-- /ko -->
                            </div>
                        </div>
                    </div>

                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="actions-toolbar">
                        <div class="secondary"><a class="action remind" href="<?= $escaper->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $escaper->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2" <?php if ($loginButtonViewModel->disabled()): ?> disabled="disabled" <?php endif; ?>><span><?= $escaper->escapeHtml(__('Sign In')) ?></span></button></div>
                    </div>
                    <div class="create-account">
                       <p><?= $escaper->escapeHtmlAttr(__("You don't have an account?")) ?></p>
                       <a  class="create-account-link" href="<?= $escaper->escapeUrl($block->getUrl('customer/account/create')) ?>">
                            <?= $escaper->escapeHtmlAttr(__('Create an Account')) ?>
                       </a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                },
                "Magento_Ui/js/core/app": {
                    "components": {
                        "showPassword": {
                            "component": "Magento_Customer/js/show-password",
                            "passwordSelector": "#pass"
                        }
                    }
                }
            }
        }
    </script>
</div>
