<?php
	$log = $block->getData('detail');
?>
<div class="page-main-actions">
	<div class="page-actions-placeholder"></div>
	<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
		<div class="page-actions-inner" data-title="Logs">
			<div class="page-actions-buttons">
        		<button id="back" title="Back" type="button" class="action- scalable back" onclick="Javascript:history.back();" data-ui-id="back-button">
    				<span>Regresar</span>
				</button>
			</div>
		</div>
	</div>
</div>

<!-- div id="page:main-container" class="row-gutter">
	<div id="page:left" class="side-col col-xs-3">
		<div data-bind="scope: 'customer_form.sections' " class="ui-tabs">
			<div class="admin__page-nav">
			    <div class="admin__page-nav-title" data-bind="css: {_collapsible: collapsible, _opened: opened &amp;&amp; collapsible}, click: toggleOpened, keyboard: {13: toggleOpened}">
			        <strong tabindex="1" data-bind="text: label, keyboard: {13: toggleOpened}">Detalle</strong>
			    </div>
			    <ul class="admin__page-nav-items items" data-bind="visible: opened, foreach: elems">
			        <li class="admin__page-nav-item _active" tabindex="2" data-bind="css: {_active: active, _loading: loading}, click: activate, keyboard: {13: activate}">
			            <a class="admin__page-nav-link" href="#" data-bind="css: {_changed: changed}, attr: {id: 'tab_' + index}" id="tab_customer_edit_tab_view_content">
			                <span data-bind="text: label">Reclamación</span>
			            </a>
			        </li>
			    </ul>
			</div>
		</div>
	</div>
</div -->
<div id="container" class="main-col col-xs-12">
	<div class="admin__old">
		<div>
		    <div data-role="spinner" data-component="customer_form.areas" class="admin__data-grid-loading-mask" style="display: none;">
		        <div class="spinner">
		            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
		        </div>
		    </div>
	    	<div data-bind="scope: 'customer_form.areas'" class="entry-edit form-inline">
			    <div data-bind="attr: {'data-area-active': active}, visible: active, foreach: elems" data-area-active="true">
					<div data-bind="css: $data.additionalClasses, html: content, visible: visible" class="admin__scope-old">
						<div class="fieldset-wrapper customer-information" style="overflow: scroll;">
						    <div class="fieldset-wrapper-title">
						        <span class="title">Detalle Log</span>
						    </div>
						    <table class="admin__table-secondary" style="width: 100%">
						        <tbody>
						        	<tr>
						            	<td valign="top"><strong>ID:</strong></td>
						            	<td><?= $log['id'] ?></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Cart ID:</strong></td>
						            	<td><?= $log['cart_id'] ?></td>
						        	</tr>
									<tr>
						            	<td valign="top"><strong>Order Number:</strong></td>
						            	<td><?= $log['order_number'] ?></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Type Request:</strong></td>
						            	<td><?= $log['type_request'] ?></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Request:</strong></td>
						            	<td><pre id="json_request"></pre></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Response:</strong></td>
						            	<td><pre id="json_response"></pre></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Payment Status:</strong></td>
						            	<td><?= $log['payment_status'] ?></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Created At:</strong></td>
						            	<td><?= $log['created_at'] ?></td>
						        	</tr>
						        </tbody>
						    </table>
						</div>
					</div>
				</div>
	    	</div>
		</div>
	</div>
</div>
<script>
	var data_request = <?= $log['request']!=""?$log['request']:"undefined" ?>;
	var data_response = <?= $log['response']!=""?$log['response']:"undefined" ?>;

	if (data_request) {
		document.getElementById("json_request").textContent = JSON.stringify(data_request, undefined, 2);
	}
	if (data_response) {
		document.getElementById("json_response").textContent = JSON.stringify(data_response, undefined, 2);
	}

</script>
