<?php
	$log = $block->getData('detail');
?>
<div class="page-main-actions">
	<div class="page-actions-placeholder"></div>
	<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
		<div class="page-actions-inner" data-title="Logs">
			<div class="page-actions-buttons">
        		<button id="back" title="Back" type="button" class="action- scalable back" onclick="Javascript:history.back();" data-ui-id="back-button">
    				<span>Regresar</span>
				</button>
			</div>
		</div>
	</div>
</div>

<div id="container" class="main-col col-xs-12">
	<div class="admin__old">
		<div>
		    <div data-role="spinner" data-component="customer_form.areas" class="admin__data-grid-loading-mask" style="display: none;">
		        <div class="spinner">
		            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
		        </div>
		    </div>
	    	<div data-bind="scope: 'customer_form.areas'" class="entry-edit form-inline">
			    <div data-bind="attr: {'data-area-active': active}, visible: active, foreach: elems" data-area-active="true">
					<div data-bind="css: $data.additionalClasses, html: content, visible: visible" class="admin__scope-old">
						<div class="fieldset-wrapper customer-information"style="overflow: scroll;">
						    <div class="fieldset-wrapper-title">
						        <span class="title">Detalle Notificación</span>
						    </div>
						    <table class="admin__table-secondary" style="width: 100%">
						        <tbody>
						        	<tr>
						            	<td valign="top"><strong>ID:</strong></td>
						            	<td><?= $log['id'] ?></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Response:</strong></td>
						            	<td><pre id="json_response_data"></pre></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Status:</strong></td>
						            	<td><?= $log['status'] ?></td>
						        	</tr>
						        	<tr>
						            	<td valign="top"><strong>Created At:</strong></td>
						            	<td><?= $log['created_at'] ?></td>
						        	</tr>
						        </tbody>
						    </table>
						</div>
					</div>
				</div>
	    	</div>
		</div>
	</div>
</div>

<script>
	var response_data = <?= $log['response_data']!=""?$log['response_data']:"undefined" ?>;

	if (response_data) {
		document.getElementById("json_response_data").textContent = JSON.stringify(response_data, undefined, 2);
	}
</script>

