stage:
  global:
    VERBOSE_COMMANDS: "-vvv"
    SCD_THREADS: 16
    SCD_STRATEGY: "quick"
    SCD_MATRIX:
      "Magento/blank": []
      "Magento/luma": []
      "Magento/backend":
        language:
          - en_US
          - es_PE
      "Wolfsellers/theme":
        language:
          - en_US
          - es_PE
  deploy:
    REDIS_USE_SLAVE_CONNECTION: true
    MYSQL_USE_SLAVE_CONNECTION: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: []
    SEARCH_CONFIGURATION:
      engine: amasty_elastic
    ELASTICSUITE_CONFIGURATION:
      es_client:
        servers: '127.0.0.1:9200'
      indices_settings:
        number_of_shards: 3
        number_of_replicas: 2