stage:
  global:
    MIN_LOGGING_LEVEL: debug
    VERBOSE_COMMANDS: '-vvv'
    SCD_ON_DEMAND: false
    SCD_MAX_EXECUTION_TIME: 1800
    SKIP_HTML_MINIFICATION: true
    SCD_NO_PARENT: false
  build:
    SKIP_SCD: false
    SCD_STRATEGY: standard
    SCD_THREADS: 4
    SCD_MATRIX:
      "Magento/backend":
        language:
          - en_US
          - es_PE
      "Wolfsellers/theme":
        language:
          - en_US
          - es_PE
      "Vass/PU":
        language:
          - en_US
          - es_PE
  deploy:
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        port: 6370
        timeout: 5
        disable_locking: 1
        bot_first_lifetime: 60
        bot_lifetime: 7200
        max_lifetime: 2592000
        min_lifetime: 60
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 50000
      consumers: [ ]
      multiple_processes:
        async.operations.all: 6
    CONSUMERS_WAIT_FOR_MAX_MESSAGES: false
    REDIS_USE_SLAVE_CONNECTION: true
    MYSQL_USE_SLAVE_CONNECTION: true
    SEARCH_CONFIGURATION:
      engine: amasty_elastic
    DATABASE_CONFIGURATION:
      _merge: true
      slave_connection:
        default:
          synchronous_replication: false
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    CACHE_CONFIGURATION:
      _merge: true
      frontend:
        default:
          id_prefix: '061_' # Prefix for keys to be preloaded
          backend_options:
            preload_keys: # List the keys to be preloaded
              - '061_EAV_ENTITY_TYPES:hash'
              - '061_GLOBAL_PLUGIN_LIST:hash'
              - '061_DB_IS_UP_TO_DATE:hash'
              - '061_SYSTEM_DEFAULT:hash'
            compress_data: 4 # 0-9
            compress_tags: 4 # 0-9
            compress_threshold: 20480 # don't compress files smaller than this value
            compression_lib: 'gzip' # snappy and lzf for performance, gzip for high compression (~69%)
      default:
        backend_options:
          use_stale_cache: false
      stale_cache_enabled:
        backend_options:
          use_stale_cache: true
      type:
        default:
          frontend: "default"
        layout:
          frontend: "stale_cache_enabled"
        block_html:
          frontend: "stale_cache_enabled"
        reflection:
          frontend: "stale_cache_enabled"
        config_integration:
          frontend: "stale_cache_enabled"
        config_integration_api:
          frontend: "stale_cache_enabled"
        full_page:
          frontend: "stale_cache_enabled"
        translate:
          frontend: "stale_cache_enabled"
    ELASTICSUITE_CONFIGURATION:
      es_client:
        servers: '127.0.0.1:9200'
      indices_settings:
        number_of_shards: 3
        number_of_replicas: 2
  post-deploy:
    WARM_UP_PAGES:
      - "category:*:default"
    WARM_UP_CONCURRENCY: 6
