stage:
  global:
    VERBOSE_COMMANDS: "-vvv"
    SCD_THREADS: 8
    SCD_STRATEGY: "quick"
    SCD_MATRIX:
      "Magento/blank": []
      "Magento/luma": []
      "Magento/backend":
        language:
          - es_PE
          - en_US
      "WolfSellers/Theme":
        language:
          - es_PE
  deploy:
    REDIS_USE_SLAVE_CONNECTION: true
    MYSQL_USE_SLAVE_CONNECTION: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: []
    SEARCH_CONFIGURATION:
      engine: amasty_elastic