<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package One Step Checkout Thank you Page 2 for Magento 2 (System)
 */
/**
 * @var $block Magento\Checkout\Block\Onepage\Success
 * @var $escaper Magento\Framework\Escaper
 */
?>
<?php
$orderObject =  $block->getOrderInfo();
if ($orderObject) {
?>
 
<div class="checkout-success">
<div class="return-home-link">
    <a href="/" class="return-home">
        &lt; Volver al Home
    </a>
</div>
    <div class="success-container">
        <h1 class="success-title">¡Gracias por tu compra!</h1>
        <div class="success-order-number">Tu ID de pedido es: <?= $orderObject->getIncrementId() ?> </div>
    </div>

        <!-- Contenido para desktop -->
        <div class="success-section">
            <div class="success-section__right success-order-details">
                <h3 class="success-order-details__title">Detalle de Compra</h3>
                
                <div class="success-order-summary">
                    <div class="success-order-summary__item success-order-summary__date">Fecha de pedido:  <?= $block->getCreatedOrder($orderObject) ?>  </div>
                </div>
                
                <div class="success-address-details">
                    <div class="success-address-details__row">
                        <div class="success-address-details__col">
                            <strong>Destinatario</strong><br>
                            <span>Nombre: <span> <?= $orderObject->getCustomerName() ?> </span></span><br>
                            <span>Apellidos: <span> <?= $orderObject->getCustomerLastName() ?> </span></span><br>
                            <span>DNI: <span><?= $orderObject->getNumeroIdentificacionPicker() ?></span></span> <br>
                            <span>Correo: <span><?= $orderObject->getCustomerEmail() ?></span></span>
                        </div>
                        <div class="success-address-details__col">
                            <strong>Mi dirección</strong><br>
                            <span>Departamento: <span><?= $orderObject->getShippingAddress()->getRegion() ?></span></span><br>
                            <span>Provincia:  <span><?= $orderObject->getShippingAddress()->getCity() ?></span></span><br>
                            <span>Distrito: <span><?= $orderObject->getShippingAddress()->getColony() ?></span></span><br>
                            <span>Número de teléfono: <span><?= $orderObject->getShippingAddress()->getTelephone() ?></span></span>
                            <span>Dirección: <span><?= $orderObject->getShippingAddress()->getStreet()[0] ?></span></span><br>
                            <span>Referencia: <span><?= $orderObject->getShippingAddress()->getReferenciaEnvio() ?></span></span><br>
                        </div>
                        <div class="success-address-details__col">
                            <strong>Forma de pago</strong><br>
                            <span><?= $block->getChildHtml('order.izipay.payment') ?></span>
                        </div>
                    </div>
                </div>
                <h3>Datos de Compra</h3>
                <div class="success-order-details__grid">
                    <div class="success-order-grid">
                        <!-- Encabezados -->
                        <div class="success-order-grid__header">Nombre de producto</div>
                        <div class="success-order-grid__header">SKU</div>
                        <div class="success-order-grid__header">Precio</div>
                        <div class="success-order-grid__header">Cantidad</div>
                        <div class="success-order-grid__header">Subtotal</div>

                        <?php foreach ($orderObject->getAllVisibleItems() as $item): ?>
                        <div class="success-order-grid__item"><?= $item->getName() ?></div>
                        <div class="success-order-grid__item"><?= $item->getSku() ?></div>
                        <div class="success-order-grid__item"><span>S/</span><?= $block->escapeHtml(number_format($item->getPriceInclTax(),2)) ?></div>
                        <div class="success-order-grid__item"><?= number_format($item->getQtyOrdered(),0) ?></div>
                        <div class="success-order-grid__item"><span>S/</span><?= $block->escapeHtml(number_format($item->getRowTotalInclTax(),2)) ?></div>
                        <?php endforeach; ?>
                    </div>
                
                    <div class="success-order-overview">
                    <div class="success-order-overview__row">
                        <span>Subtotal</span>
                        <span>S/<?= $block->escapeHtml(number_format($orderObject->getSubtotal(),2)) ?></span>
                    </div>
                    <div class="success-order-overview__row">
                        <span>Costo de envío</span>
                        <span>S/<?= $block->escapeHtml(number_format($orderObject->getShippingAmount(),2)) ?></span>
                    </div>
                    <div class="success-order-overview__row success-order-overview__total">
                        <strong>Total</strong>
                        <strong>S/<?= $block->escapeHtml(number_format($orderObject->getGrandTotal(),2)) ?></strong>
                    </div>
                </div>
                </div>
                <!-- Mensaje de confirmación -->
                <div class="success-message">
                        Tu pedido ha sido recibido. ¡Gracias por comprar con nosotros!
                    </div>
        </div>

        <!-- Contenido para mobile -->
        <div class="success-summary__dates">
            <div class="success-summary__date-item success-summary__date-item--success">
                <span class="success-summary__date-label">Fecha de pedido: </span>
                <span class="success-summary__date-value"><?= $block->getCreatedOrder($orderObject) ?> </span>
            </div>
        </div>
        <div class="success-summary__section">
            <button class="success-summary__collapsible collapsible-open" type="button">Destinatario</button>
            <div class="success-summary__content">
                <p class="success-summary__info"><span>Nombre:</span> <?= $orderObject->getCustomerName() ?></p>
                <p class="success-summary__info"><span>Apellidos:</span> <?= $orderObject->getCustomerLastName() ?></p>
                <p class="success-summary__info"><span>DNI:</span> <?= $orderObject->getNumeroIDentificacionPicker() ?></p>
                <p class="success-summary__info"><span>Correo:</span> <?= $orderObject->getCustomerEmail() ?></p>
            </div>

            <button class="success-summary__collapsible collapsible-open" type="button">Mi dirección</button>
            <div class="success-summary__content">
                <p class="success-summary__info"><span>Departamento:</span> <?= $orderObject->getShippingAddress()->getRegion() ?></p>
                <p class="success-summary__info"><span>Provincia:</span> <?= $orderObject->getShippingAddress()->getCity() ?></p>
                <p class="success-summary__info"><span>Distrito:</span> <?= $orderObject->getShippingAddress()->getColony() ?></p>
                <p class="success-summary__info"><span>Número de teléfono:</span> <?= $orderObject->getShippingAddress()->getTelephone() ?></p>
                <p class="success-summary__info"><span>Dirección:</span> <?= $orderObject->getShippingAddress()->getStreet()[0] ?></p>
                <p class="success-summary__info"><span>Referencia:</span> <?= $orderObject->getShippingAddress()->getReferenciaEnvio() ?></p>
            </div>

            <button class="success-summary__collapsible collapsible-open" type="button">Forma de pago</button>
            <div class="success-summary__content">
                <p class="success-summary__info"><?= $block->getChildHtml('order.izipay.payment') ?></p>
            </div>

            <button class="success-summary__collapsible collapsible-open" type="button">Detalle de la compra</button>
            <div class="success-summary__content">
            <?php foreach ($orderObject->getAllVisibleItems() as $item): ?>
                <p class="success-summary__info"><span>Nombre de producto:</span> <?= $item->getName() ?></p>
                <p class="success-summary__info"><span>SKU:</span> <?= $item->getSku() ?></p>
                <p class="success-summary__info"><span>Precio:</span> S/<?= $block->escapeHtml(number_format($item->getPriceInclTax(),2)) ?></p>
                <p class="success-summary__info"><span>Cantidad:</span> <?= number_format($item->getQtyOrdered(),0) ?></p>
                <p class="success-summary__info"><span>Subtotal:</span> S/<?= $block->escapeHtml(number_format($item->getRowTotalInclTax(),2)) ?></p>
                <div class="success-summary__totals">
                    <p class="success-summary__total"><span>Subtotal:</span> S/<?= $block->escapeHtml(number_format($orderObject->getSubtotal(),2)) ?></p>
                    <p class="success-summary__total"><span>Costo de envío:</span> S/<?= $block->escapeHtml(number_format($orderObject->getShippingAmount(),2)) ?></p>
                    <p class="success-summary__total success-summary__total--bold"><strong>Total:</strong> S/<?= $block->escapeHtml(number_format($orderObject->getGrandTotal(),2)) ?></p>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function () {
            // Activar colapsadores solo en mobile
            $('.success-summary__collapsible').each(function () {
                var button = $(this);
                button.addClass('collapsible-open');
                button.on('click', function () {
                    var content = button.next();
                    if (content.css('display') === 'block') {
                        content.css('display', 'none');
                        button.removeClass('collapsible-open');
                    } else {
                        content.css('display', 'block');
                        button.addClass('collapsible-open');
                    }
                    checkAllOpen();
                });

                // Inicializar desplegados
                button.next().css('display', 'block');
            });

            function checkAllOpen() {
                var allOpen = $('.success-summary__collapsible').toArray().every(function (button) {
                    return $(button).hasClass('collapsible-open');
                });

                var orderDetails = $('.success-section__right .success-order-details');
                if (allOpen) {
                    orderDetails.css('display', 'none');
                } else {
                    orderDetails.css('display', 'block');
                }
            }

            // Eliminar la clase page-title-wrapper si existe
            $('.page-title-wrapper').remove();
        });
    });
</script>
<?php 
}
?>