<?php
/**
 * @copyright Copyright (c) 2024 VASS
 * @author VASS Team
 */

/**
 * @var \Vass\CardsSlider\Block\Widget\CardsSlider $block
 * @var \Magento\Framework\Escaper $escaper
 */

$images = $block->getImages();
$title = $block->getTitle();
$description = $block->getDescription();
$textUrl = $block->getTextUrl();
$url = $block->getUrl();
$count = count($images);

?>
<div class="card-slider__wrapper">
    <div class="card-slider swiper">
        <div class="swiper-wrapper">
            <?php for ($i = 0; $i < $count; $i++): ?>
                <?php if ($images[$i]): ?>
                    <div class="swiper-slide">
                        <div class="card-slider__wrapper">
                            <div class="card-slider-info-img">
                                <img class="card-slider-img" src="<?= /** @noEscape */ $images[$i]; ?>" />
                            </div>
                            <div class="card-slider__content">
                                <h3 class="card-slider-title">
                                    <?= /** @noEscape */ $title[$i]; ?>
                                </h3>
                                <p class="card-slider-description">
                                    <?= /** @noEscape */ $description[$i]; ?>
                                </p>
                                <a class="card-slider-link" href="<?= /** @noEscape */ $url[$i]; ?>">
                                    <?= /** @noEscape */ $textUrl[$i]; ?>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
        <div class="swiper-pagination-card-slider"></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Vass_CardsSlider/js/cards_slider": {}
        }
    }
</script>
