<?php
/**
 * @copyright Copyright (c) 2024 Vass
 * @package Vass_Sales
 * @author Vass Team
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */

?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
        <div class="<?= $block->escapeHtmlAttr($_code) ?>">
            <div <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <div>
                        <?= $block->escapeHtml($_total->getLabel()) ?>
                    </div>
                <?php else : ?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif ?>
            </div>

            <div <?= /* @noEscape */ $block->getValueProperties() ?>
                data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                <?php else : ?>
                    <?= /* @noEscape */ $block->formatValue($_total) ?>
                <?php endif?>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach?>
