<?php
/**
 * @copyright Copyright (c) 2024 VASS
 * @author VASS Team
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<section class="amsearch-input-wrapper"
         data-bind="
            css: {
                '-dynamic-width': data.isDynamicWidth,
                '-match': $data.readyForSearch(),
                '-typed': inputValue && inputValue().length
            }">
    <input type="text"
           name="q"
           placeholder="<?= $escaper->escapeHtmlAttr(__('What are you looking for?')) ?>"
           class="amsearch-input"
           maxlength="128"
           role="combobox"
           aria-haspopup="false"
           aria-autocomplete="both"
           autocomplete="off"
           aria-expanded="false"
           data-amsearch-block="input"
           enterkeyhint="enter"
           data-bind="
                afterRender: initInputValue,
                hasFocus: focused,
                value: inputValue,
                event: {
                    keypress: onEnter
                },
                valueUpdate: 'input'">
    <!-- ko template: { name: templates.loader } --><!-- /ko -->
    <button class="amsearch-button -close -clear -icon"
            style="display: none"
            data-bind="
                event: {
                    click: inputValue.bind(this, '')
                },
                attr: {
                    title: $t('Clear Field')
                },
                visible: inputValue && inputValue().length">
    </button>
    <button class="amsearch-button -loupe -clear -icon"
            data-bind="
                event: {
                    click: search
                },
                css: {
                    '-disabled': !$data.match()
                },
                attr: {
                    title: $t('Search')
                }">
                <icon class="icon icon-search" />
    </button>
</section>
