<?php
/** @var $block \Magento\Checkout\Block\Onepage\Success */

/** @var $viewModel \WolfSellers\Checkout\ViewModel\SuccessOrder */
$viewModel = $block->getData('viewModel');
?>

<?php if (!$viewModel->isPickup($block->getOrderId())): ?>
    <div class="general-order-data">
        <div class="order-consecutive-id">
            <span>Order No:<a href="<?=$block->getViewOrderUrl()?>"><?= $block->getOrderId(); ?></a></span>
        </div>
        <div class="order-info">
            <p>
                <?= __("Se enviará un mensaje con <b>toda la información de tu pedido</b> por correo electrónico cuando tu pedido esté lsito para ser entregado.")?>
                <?= __("Por favor te pedimos que esperes a la confirmación")?>
            </p>
        </div>
        <a class="order-back-to-store" href="<?=$block->getBaseUrl()?>"><?= __("Regresar a la tienda"); ?></a>
    </div>
<?php endif; ?>
