<?php
/** @var $block \Magento\Checkout\Block\Onepage\Success */

/** @var $viewModel \WolfSellers\Checkout\ViewModel\SuccessOrder */
$viewModel = $block->getData('viewModel');
?>

<?php if (!$viewModel->isPickup($block->getOrderId())): ?>
    <div class="general-order-data">
        <div class="order-consecutive-id">
            <span>Orden No:<a href="<?=$block->getViewOrderUrl()?>"><?= $block->getOrderId(); ?></a></span>
        </div>
        <div class="order-info">
            <p>
                <?= __("Se enviará un mensaje con <b>toda la información de tu pedido</b> por correo electrónico cuando tu pedido esté listo para ser entregado.")?>
                <?= __("Por favor te pedimos que esperes a la confirmación")?>
            </p>
        </div>
        <a class="order-back-to-store" href="<?=$block->getBaseUrl()?>"><?= __("Regresar a la tienda"); ?></a>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require([
        'Magento_Customer/js/customer-data',
        'domReady!'
    ], function (customerData) {
        var sections = ['cart'];
        customerData.invalidate(sections);
        customerData.reload(sections, true);
    });
</script>
