<?php
    /** @var $block \WolfSellers\Bopis\Block\Order\Email\Addresses */

    /** @var  $viewModel \WolfSellers\Bopis\ViewModel\GeneralOrder */
    $viewModel = $block->getData('viewModel');

    /** @var $order \Magento\Sales\Api\Data\OrderInterface */
    $order = $this->getOrder();

    $billingInformation = $viewModel->getCustomerOrderBillingInformation($block->getOrderId());
    $shippingAddress = $order->getShippingAddress();

    $horarioDeEntrega = $viewModel->getRealAddrOptionValue('horarios_disponibles',
        $shippingAddress->getHorariosDisponibles());

    $horarioTxt = $viewModel->getAllSchedule($horarioDeEntrega, $order->getCreatedAt());
?>
<table>
    <tbody>
        <tr>
            <td class="address-details">
                <h3>Información de contacto</h3>
                <p>
                    <?php if($order->getCustomerIsGuest()): ?>
                        <?=ucfirst($order->getCustomerNombre())?> <br>
                        <?=ucfirst($order->getCustomerApellido())?> <br>
                    <?php else: ?>
                        <?=$order->getCustomerFirstname()?> <br>
                        <?=$order->getCustomerLastname()?> <br>
                    <?php endif; ?>

                    <?php if($billingInformation['type_id'] == 'DNI'):?>
                        <?=$billingInformation['type_id']?> : <?=$billingInformation['id_number']?><br>
                    <?php else: ?>
                        <?= __("Tipo de documento")?>: <?=$billingInformation['type_id']?><br>
                        <?= __("Número de documento")?> : <?=$billingInformation['id_number']?><br>
                    <?php endif; ?>
                    <?=$billingInformation['email']?> <br>
                    <?=$billingInformation['tel']?> <br>
                </p>
            </td>

            <td class="address-details">
                <h3>Información de entrega</h3>
                <p>
                    <?php if ($block->getIsPickup()): ?>
                        <?= $shippingAddress->getName() ?> <br>
                        <?= implode(" ", ($shippingAddress->getStreet() ?? [])) ?> <br>
                        <?= $horarioTxt['fecha'] ?? $horarioTxt['default-instore'] ?> <br>
                        <?= $horarioTxt['horario'] ?? "" ?>
                        <?php if($shippingAddress->getNumeroIdentificacionPicker()): ?>
                            <?= __("Número de documento")?>: <?= $shippingAddress->getNumeroIdentificacionPicker() ?><br>
                            <?= __("Nombre y Apellido")?> : <?= $shippingAddress->getNombreCompletoPicker() ?><br>
                        <?php endif; ?>
                    <?php else: ?>
                        <?= implode(" ", ($shippingAddress->getStreet() ?? [])) ?>
                        <?= $shippingAddress->getPostcode() ?>,
                        <?= $shippingAddress->getData('colony') ?> -
                        <?= $shippingAddress->getCity() ?> -
                        <?= $shippingAddress->getRegion() ?> <br>
                        <?= $shippingAddress->getData('referencia_envio') ?> <br>
                        <?= $horarioTxt['fecha'] ?? $horarioTxt['default-msj'] ?> <br>
                        <?= $horarioTxt['horario'] ?? "" ?>
                    <?php endif; ?>
                </p>
            </td>
        </tr>
    </tbody>
</table>
