<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\GoogleTagManager\Block\Ga;
?>
<?php
/** @var \WolfSellers\GoogleTagManager\Block\ListJson $block */
$product = $block->getCurrentProduct();

$attributes = $product->getAttributes();
$category = '';
$subcategory = '';
$brand = '';

$gender = '';
$size = '';
foreach($attributes as $attribute){
    if($attribute->getName() === 'categoria') {
        $category = $attribute->getFrontend()->getValue($product);
    }
    if($attribute->getName() === 'sub_categoria') {
        $subcategory = $attribute->getFrontend()->getValue($product);
    }
    //if($attribute->getName() === 'brand_ids') {
    if($attribute->getName() === 'manufacturer') {
        $brand = $attribute->getFrontend()->getValue($product);
    }
    if($attribute->getName() === 'genero') {
        $gender = $attribute->getFrontend()->getValue($product);
    }
    if($attribute->getName() === 'tamano') {
        $size = $attribute->getFrontend()->getValue($product);
    }
}
$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
    ->init($product, 'product_base_image')->getUrl();

$rules = $block->getRules($product->getId);

var_dump($rules);die();
?>

<h1>ALEJANDRA</h1>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_GoogleTagManager/js/actions/product-detail": {
                "product":{
                    "id": "<?=$block->escapeJs($product->getId());?>",
                    "totalValue": "<?=$block->escapeJs($product->getFinalPrice());?>",
                    "name": "<?=$block->escapeJs($product->getName());?>",
                    "sku": "<?=$block->escapeJs($product->getSku());?>",
                    "category": "<?=$block->escapeJs($category);?>",
                    "sub_categoria": "<?=$block->escapeJs($subcategory);?>",
                    "brand": "<?=$block->escapeJs($brand);?>",
                    "productURL": "<?=$block->escapeJs($product->getProductUrl());?>",
                    "imageURL": "<?=$block->escapeJs($imageUrl);?>",
                    "genero": "<?=$block->escapeJs($gender);?>",
                    "tamano": "<?=$block->escapeJs($size);?>"
                },
                "currencyCode": "<?=$block->getCurrencyCode();?>"
            }
        }
    }
</script>
