<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\GoogleTagManager\Block\Ga;
use WolfSellers\GoogleTagManager\Block\ListJson;

?>
<?php
/** @var ListJson $block */
$product = $block->getCurrentProduct();

$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
    ->init($product, 'product_base_image')->getUrl();

$rules = $block->getRules($product->getId());
$data = [];
if ($rules) {
    foreach ($rules as $rule) {
        $data[] = $rule;
    }
}
$data = implode(', ', $data);

$category = $product->getData('categoria') ?? '';
$subcategory = $product->getData('sub_categoria') ?? '';
$family = $product->getData('familia') ?? '';
$brand = $product->getAttributeText('manufacturer') ?? '';
$gender = $product->getAttributeText('genero') ?? '';
$size = $product->getData('tamano') ?? '';
$price = number_format($product->getFinalPrice(), 2);

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_GoogleTagManager/js/actions/product-detail": {
                "product":{
                    "id": "<?= $block->escapeJs($product->getId()); ?>",
                    "totalValue": "<?= $block->escapeJs($price); ?>",
                    "name": "<?= $block->escapeJs($product->getName()); ?>",
                    "sku": "<?= $block->escapeJs($product->getSku()); ?>",
                    "category": "<?= $block->escapeJs($category); ?>",
                    "sub_categoria": "<?= $block->escapeJs($subcategory); ?>",
                    "familia": "<?= $block->escapeJs($family); ?>",
                    "brand": "<?= $block->escapeJs($brand); ?>",
                    "productURL": "<?= $block->escapeJs($product->getProductUrl()); ?>",
                    "imageURL": "<?= $block->escapeJs($imageUrl); ?>",
                    "genero": "<?= $block->escapeJs($gender); ?>",
                    "tamano": "<?= $block->escapeJs($size); ?>",
                    "promotion": "<?= $block->escapeJs($data); ?>"
                },
                "currencyCode": "<?= $block->getCurrencyCode(); ?>"
            }
        }
    }
</script>
