<?php
/** @var \Magento\Framework\View\Element\AbstractBlock $block */

/** @var  $viewModel \WolfSellers\Bopis\ViewModel\RememberMe */
$viewModel = $block->getData('viewModel');
?>

<?php if ($viewModel->isEnabled()): ?>
    <div class="admin__field field-rememberme">
        <label for="rememberme" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Remember Me')) ?></span>
        </label>
        <div class="admin__field-control">
            <input id="rememberme"
                   class="admin__field-control"
                   type="checkbox"
                   name="rememberme"
                   data-validate="{required:false}"
                   value="true"
            />
        </div>
        <!--persistent_remember_me-->
    </div>
<?php endif; ?>
