<?php
/**
 * @copyright Copyright (c) 2024 VASS
 * @author VASS Team
 */

/**
 * @var $block Magento\Checkout\Block\Onepage
 * @var $escaper Magento\Framework\Escaper
 * @var $onepageDataProvider Amasty\CheckoutCore\ViewModel\OnepageDataProvider
 * @var $bundleService Amasty\CheckoutCore\Model\Optimization\BundleService
 * @var $styleSwitcher Amasty\CheckoutCore\ViewModel\StyleSwitcherProvider
 * @var $secureRenderer Magento\Framework\View\Helper\SecureHtmlRenderer
 */

$onepageDataProvider = $block->getData('amcheckoutOnepageDataProvider');
$bundleService = $block->getData('bundleService');
$styleSwitcher = $block->getData('amcheckoutStyleSwitcher');
$design = $styleSwitcher->isModernCheckoutDesign() ? 'modern' : 'classic';
$layout = $styleSwitcher->getDesignLayout();
$serializedCheckoutConfig = /* @noEscape */ $block->getSerializedCheckoutConfig();

$messagesMixinScript = <<<SCRIPT
    require.config({
            config: {
                mixins: {
                    'Magento_Ui/js/view/messages': {
                        'Amasty_CheckoutCore/js/view/messages-mixin': true
                    }
                }
            }
        });
SCRIPT;

$configsScript = <<<SCRIPT
    window.checkoutConfig = {$serializedCheckoutConfig};
    window.checkoutDesign = "{$escaper->escapeHtml($design)}";
    window.checkoutLayout = "{$escaper->escapeHtml($styleSwitcher->getLayoutTemplate())}";
    // Create aliases for customer.js model from customer module
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
SCRIPT;

$blockLoaderScript = <<<SCRIPT
    require([
         'mage/url',
         'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
            blockLoader('{$escaper->escapeJs($escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')))}');
            return url.setBaseUrl('{$escaper->escapeJs($escaper->escapeUrl($block->getBaseUrl()))}');
        });
SCRIPT;
?>

<div id="checkout"
     data-bind="scope:'checkout'"
     class="checkout-container am-checkout -<?= /* @noEscape */ $design?> -layout-<?= /* @noEscape */ $layout?>"
     data-amcheckout-js="checkout">
    <div class="checkout-header">

        <h1 class="title"><?= $escaper->escapeHtml($onepageDataProvider->getTitle()); ?></h1>
        <!-- ko ifnot: window.checkoutConfig.isCustomerLoggedIn  -->
            <div class="description">
                <?= $escaper->escapeHtml($onepageDataProvider->getDescription(), ['a', 'b', 'i', 'u', 's', 'strong']); ?>
            </div>
        <!-- /ko -->
    </div>

    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?=
            /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?= $escaper->escapeHtml(__('Loading...')); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
            }
        }
    </script>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $messagesMixinScript, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $configsScript, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $blockLoaderScript, false) ?>

    <?php if ($bundleService->canCollectBundle()): ?>
        <?php
        $collectScriptPath = \Amasty\CheckoutCore\Model\Optimization\BundleService::COLLECT_SCRIPT_PATH;
        $collectBundleScript = <<<SCRIPT
            require([
                'rjsResolver',
                'underscore',
                '{$collectScriptPath}',
            ], function(requireResolver, _, createBundle) {
                requireResolver(_.debounce(createBundle, 1000));
            });
        SCRIPT;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $collectBundleScript, false) ?>
    <?php endif; ?>
</div>
