<?php
/**
 * @copyright Copyright (c) 2024 Vass
 * @package Vass_Customer
 * @author Vass Team
 */

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>

<div class="block block-addresses-list">
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>
            <div class="addresses-wrapper additional-addresses">
                <?php foreach ($_pAddsses as $address) : ?>
                    <div class="address-item">
                        <div class="address-data">
                            <div class="address-title">
                                <?= $block->escapeHtml(_('Address Name')) ?>
                            </div>

                            <div class="field firstname">
                                <span><?= $block->escapeHtml($address->getFirstname()) ?></span>
                                <span><?= $block->escapeHtml($address->getLastname()) ?></span>
                            </div>

                            <div class="field streetaddress">
                                <span><?= $block->escapeHtml($block->getStreetAddress($address)) ?></span>
                            </div>

                            <div class="field city">
                                <span><?= $block->escapeHtml($address->getCity()) ?></span>
                                <span><?= $block->escapeHtml($address->getRegion()->getRegion()) ?></span>
                                <span><?= $block->escapeHtml($block->getCountryByCode($address->getCountryId())) ?></span>
                                <span><?= $block->escapeHtml($address->getPostcode()) ?></span>
                            </div>

                            <div class="field phone">
                                <span><?= $block->escapeHtml($address->getTelephone()) ?></span>
                            </div>
                        </div>

                        <div class="address-actions">
                            <a class="action secondary edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>">
                                <span><?= $block->escapeHtml(__('Edit')) ?></span>
                            </a>
                            <a class="action secondary delete" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>">
                                <span><?= $block->escapeHtml(__('Delete')) ?></span>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <?php if ($block->getChildHtml('pager')) : ?>
                <div class="customer-addresses-toolbar toolbar bottom">
                    <?= $block->getChildHtml('pager') ?>
                </div>
            <?php endif ?>
        <?php else : ?>
            <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
        <?php endif ?>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="button"
                        role="add-address"
                        title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>"
                        class="action primary add">
                    <span><?= $block->escapeHtml(__('Add New Address')) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "div a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
