<?php
/** @var \WolfSellers\Bopis\Block\Adminhtml\Order\View\Footer $block */

$entregar = $block->isEntregarAvailable();
$hold = $block->isHoldAvailable();
$order = $block->getOrder();
$isDelivered = $block->isDelivered();
$isHolded = $block->isHolded();
$isComplete = $block->isComplete();
$comments = $block->isCompleteComments();
?>


<section class="admin__page-section bopis-footer">
    <div class="admin__page-section-content">
        <?php if ($entregar && !$isHolded && $block->getAdminUserType() == 1): ?>
            <button name="btn-entregar"
                    value="Entregar"
                    class="btn-entregar <?= $entregar ? "" : "deshabilitado" ?>
                        <?=$block->popupEnabled() ? "popupEnabled" : "" ?>"
                <?= $entregar ? "" : 'disabled="disabled"' ?>
                    data-order-id="<?= $order->getEntityId() ?>"
            >
                Entregar Orden
            </button>
        <?php endif; ?>
        <?php if (!$isHolded && $block->getAdminUserType() == 1): ?>
            <button name="btn-detener"
                    value="Detener"
                    class="btn-detener <?= $hold ? "" : "deshabilitado" ?>"
                <?= $hold ? "" : 'disabled="disabled"' ?>
                    data-order-id="<?= $order->getEntityId() ?>"
            >
                Detener Orden
            </button>
        <?php endif; ?>
    </div>
</section>

<?php if($isComplete): ?>
    <form action="<?= $block->escapeUrl($block->getUrl("bopis/complete/save"))?>" method="post"
          id="form-comlete-comments">
        <input name="form_key" type="hidden"  value="<?= $block->getFormKey() ?>" />
        <h2>Añadir comentarios de la orden:</h2>
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label for="complete_comments"></label>
            </div>
            <input name="order_id" id="order_id" type="hidden" value="<?= $order->getEntityId() ?>">
            <textarea name="complete_comments" id="complete_comments" placeholder="Observaciones" class="required required-entry"></textarea>
        </div>
        <input type="submit" value="Confirmar" class="btn" />
    </form>
    <section class="admin__page-section bopis-footer">
        <div class="admin__page-section-content">
            <table>
                <thead>
                <tr>
                    <th>Comentarios de la entrega realizada</th>
                </tr>
                </thead>
                <tbody>
                <?php if($comments):?>
                    <?php foreach($comments as $comment):?>
                        <tr>
                            <td><?php echo $comment;?></td>
                        </tr>
                    <?php endforeach;?>
                <?php else: ?>
                    <tr>
                        <td>Sin comentarios</td>
                    </tr>
                <?php endif;?>
                </tbody>
            </table>
        </div>
    </section>
<?php endif; ?>
<?php if ($isHolded): ?>
    <section class="admin__page-section bopis-footer">
        <div class="admin__page-section-content">
            <table>
                <thead>
                <tr>
                    <th>Comentarios del pedido detenido</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><?= $block->getOrder()->getData("bopis_hold_comments") ?? "Sin comentarios" ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>
<?php endif; ?>
<div id="popup-modal-entregar" style="display: none">

    <form action="<?= $block->escapeUrl($block->getUrl("bopis/deliver/save")) ?>" method="post"
          id="bopis-deliver">
        <h2>Añadir comentarios de la orden:</h2>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>
        <input name="order_id" type="hidden" value="<?= $order->getEntityId() ?>"/>
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label for="bopis_deliver_comment"></label>
            </div>
            <textarea name="bopis_deliver_comment" id="bopis_deliver_comment" placeholder="Observaciones"
                      class="required required-entry"></textarea>
        </div>


        <input type="submit" value="Confirmar" class="bopis-popup-btn-confirmar"/>
        <input type="button" value="Regresar" class="bopis-popup-btn-regresar"/>
    </form>
</div>
<div id="popup-modal-hold" style="display: none">

    <h2>Detener Orden:</h2>
    <form action="<?= $block->escapeUrl($block->getUrl("bopis/hold/save")) ?>" method="post"
          id="bopis-hold">
        <input name="order_id" type="hidden" value="<?= $order->getEntityId() ?>"/>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label for="bopis_hold_reason"></label>
            </div>
            <select name="bopis_hold_reason" id="bopis_hold_reason"
                    class="required required-entry admin__control-select">
                <option value="" selected>Seleccionar motivo</option>
                <?php foreach ($block->getHoldReasons() as $holdReason): ?>
                    <option value="<?= $holdReason ?>"><?= $holdReason ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label for="bopis_hold_comment"></label>
            </div>
            <textarea name="bopis_hold_comment" id="bopis_hold_comment" placeholder="Observaciones"
                      class="required required-entry"></textarea>
        </div>

        <input type="submit" value="Confirmar" class="bopis-popup-btn-confirmar"/>
        <input type="button" value="Regresar" class="bopis-popup-btn-regresar"/>
    </form>
</div>
<div id="popup-modal-preparar" style="display: none">

    <form action="<?= $block->escapeUrl($block->getUrl("bopis/prepare/save")) ?>" method="post"
          id="bopis-prepare">
        <h2>Indicar que el paquete está listo para ser entregado al cliente:</h2>
        <ul>
            <li>Recuerda separar el producto del almacén</li>
            <li>Revisa que el producto esté en buen estado</li>
            <li>Una vez listo y seperado, da click en confirmar</li>
        </ul>
        <input name="order_id" type="hidden" value="<?= $order->getEntityId() ?>"/>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>

        <input type="submit" value="Confirmar" class="bopis-popup-btn-confirmar"/>
        <input type="button" value="Regresar" class="bopis-popup-btn-regresar"/>
    </form>
</div>

<div id="popup-modal-enviar" style="display: none">

    <form action="<?= $block->escapeUrl($block->getUrl("bopis/shipping/save")) ?>" method="post"
          id="bopis-prepare">
        <h2>Indicar que el paquete está listo para ser enviado al cliente:</h2>
        <ul>
            <li>Custom TEXT</li>
        </ul>
        <input name="order_id" type="hidden" value="<?= $order->getEntityId() ?>"/>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>

        <input type="submit" value="Confirmar" class="bopis-popup-btn-confirmar"/>
        <input type="button" value="Regresar" class="bopis-popup-btn-regresar"/>
    </form>
</div>
<div id="form-confirmacion" style="display: none">

    <form action="<?= $block->escapeUrl($block->getUrl("bopis/confirmar/save")) ?>" method="post"
          id="bopis-confirm-verification">
        <input name="order_id" type="hidden" value="<?= $order->getEntityId() ?>"/>
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>
        <input name="tipo_verificacion" type="hidden" id="bopis-confirmation-type-input" value=""/>
    </form>
</div>
