<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \WolfSellers\Bopis\Block\Adminhtml\Order\View\Items $block
 */
$_order = $block->getOrder(); ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
        <tr class="headings">
            <?php $i = 0;
            $columns = $block->getColumns();
            $lastItemNumber = count($columns) ?>
            <?php foreach ($columns as $columnName => $columnTitle) : ?>
                <?php $i++; ?>
                <th class="col-<?= $block->escapeHtmlAttr($columnName) ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= $block->escapeHtml($columnTitle) ?></span></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0;
        /** @var \Magento\Sales\Model\Order\Item $_item */
        foreach ($_items as $_item) : ?>
            <?php if ($_item->getParentItem()) :
                continue;
            else :
                $i++;
            endif; ?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
            <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
            <tr>
                <td colspan="<?=$lastItemNumber-2?>"></td>
                <td colspan="2">
                    <table width="100%">
                        <tr>
                            <td>Subtotal</td>
                            <td><?=$_order->formatPrice($_order->getSubtotal())?></td>
                        </tr>
                        <tr>
                            <td>Descuento:</td>
                            <td><?=$_order->formatPrice($_order->getDiscountAmount())?></td>
                        </tr>
                        <tr>
                            <td>Costo de envío</td>
                            <td><?=$_order->formatPrice($_order->getShippingAmount())?></td>
                        </tr>
                        <tr>
                            <td><b>Total</b></td>
                            <td><?=$_order->formatPrice($_order->getGrandTotal())?></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
