<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Backend\Block\Page\Header */
$part = $block->getShowPart();
/** @var \WolfSellers\Backend\Helper\Data $helper */
$helper = $this->helper('WolfSellers\Backend\Helper\Data');
$imgSystem = $helper->getConfig('admin/general/image');
$urlMedia = $helper->getBaseUrlMedia();
$enabledModule = $helper->getConfig('admin/general/show_image');

if($helper->isBopis()) :
?>
<script>
    document.body.classList.add("admin-bopis");
    require(['jquery', 'domReady!'], function ($) {
        $("#account-signout-bopis").addClass("level-0").detach().appendTo('#nav');
        if($(".nav-bopis-ordenes").length < 1) {
            $('#nav').prepend('<li class="nav-bopis-ordenes level-0"><a onclick="return false;">Órdenes</li>');
        }
    });
</script>
<?php
endif;
if ($part === 'logo') : ?>
    <?php if ($enabledModule): ?>
        <div class="image-system-admin-login"><img src="<?php echo $urlMedia . 'magepow/backendimage/' . $imgSystem ?>">
        </div>
    <?php endif; ?>
    <?php $edition = $block->hasEdition() ? 'data-edition="' . $block->escapeHtml($block->getEdition()) . '"' : ''; ?>
    <?php $logoSrc = ($block->hasLogoImageSrc()) ? $block->escapeHtml($block->getLogoImageSrc()) : 'images/magento-logo.svg' ?>
    <!--  <div class="header-logo">

     </div> -->
    <a
        href="<?= $block->escapeUrl($block->getHomeLink()) ?>"
        <?= /* @noEscape */
        $edition ?>
        class="logo">
        <img class="logo-img" src="<?= /* @noEscape */
        $block->getViewFileUrl($logoSrc) ?>"
             alt="<?= $block->escapeHtml(__('Magento Admin Panel')) ?>"
             title="<?= $block->escapeHtml(__('Magento Admin Panel')) ?>"/>
    </a>
    <?php if (!empty($block->getUser())):?>

        <?php if ($block->getUser()->getData('user_type') == '1' || $block->getUser()->getData('user_type') == '2'): ?>
            <div class="admin-user">

            </div>
            <nav class="nav-admin-user">
                <ul>
                    <li>
                        <span class="user-welcome">Bienvenido</span>
                    </li>
                    <li>
                    <span
                        class="admin-user-account-text"><?= $block->escapeHtml($block->getUser()->getFirstName() . " " . $block->getUser()->getLastName()) ?></span>
                        <?php if (!empty($block->getUser()->getData('source_code')) && $block->getUser()->getData('user_type') == 1): ?>
                            <span class="admin-user-account-source-code">
                                <?= "Tienda: ".$helper->getSourceName($block->getUser()->getData('source_code')) ?>
                            </span>
                        <?php endif; ?>
                        <?php if ($block->getUser()->getData('user_type') == 2): ?>
                            <span class="admin-user-account-source-code">
                                <?= $helper->getWebsiteManagerText() ?>
                            </span>
                        <?php endif; ?>
                    </li>
                    <li id="account-signout-bopis">
                        <a
                            href="<?= /* @noEscape */
                            $block->getLogoutLink() ?>"
                            class="account-signout"
                            title="<?= $block->escapeHtml(__('Cerrar Sesión')) ?>">
                            <?= $block->escapeHtml(__('Cerrar Sesión')) ?>
                        </a>
                    </li>
                </ul>
            </nav>
        <?php endif; ?>
    <?php endif; ?>
<?php elseif ($part === 'user') : ?>
    <?php if ($block->getUser()->getData('user_type') == '1' || $block->getUser()->getData('user_type') == '2'): ?>

    <?php else: ?>
        <div class="admin-user admin__action-dropdown-wrap">
            <a
                href="<?= /* @noEscape */
                $block->getUrl('adminhtml/system_account/index') ?>"
                class="admin__action-dropdown"
                title="<?= $block->escapeHtml(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="admin__action-dropdown-text">
                    <span
                        class="admin-user-account-text"><?= $block->escapeHtml($block->getUser()->getUserName()) ?></span>
                </span>
            </a>
            <ul class="admin__action-dropdown-menu">
                <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')) : ?>
                    <li>
                        <a
                            href="<?= /* @noEscape */
                            $block->getUrl('adminhtml/system_account/index') ?>"
                            <?= /* @noEscape */
                            $block->getUiId('user', 'account', 'settings') ?>
                            title="<?= $block->escapeHtml(__('Account Setting')) ?>">
                            <?= $block->escapeHtml(__('Account Setting')) ?> (<span
                                class="admin-user-name"><?= $block->escapeHtml($block->getUser()->getUserName()) ?></span>)
                        </a>
                    </li>
                <?php endif; ?>
                <li>
                    <a
                        href="<?= /* @noEscape */
                        $block->getBaseUrl() ?>"
                        title="<?= $block->escapeHtml(__('Customer View')) ?>"
                        target="_blank" class="store-front">
                        <?= $block->escapeHtml(__('Customer View')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= /* @noEscape */
                        $block->getLogoutLink() ?>"
                        class="account-signout"
                        title="<?= $block->escapeHtml(__('Cerrar Sesión')) ?>">
                        <?= $block->escapeHtml(__('Cerrar Sesión')) ?>
                    </a>
                </li>
            </ul>
        </div>
    <?php endif; ?>

<?php elseif ($part === 'other') : ?>
    <?= $block->getChildHtml() ?>
<?php endif; ?>
