<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \WolfSellers\GoogleTagManager\Block\ListJson $block */
?>

<div id="checkout-shipping-load">
    <!-- Content loaded dynamically -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_GoogleTagManager/js/actions/checkout": {
                "cart": <?= /* @noEscape */ $block->getCartContentExtended() ?>,
                "currencyCode": "<?=$block->getCurrencyCode();?>",
                "dataUser": <?=$block->getCustomerInfo();?>
            }
        }
    }
</script>
