<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \WolfSellers\GoogleTagManager\Block\Ga $block */
$orderData = $block->getOrdersDataArray()[0];
?>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        $(document).trigger('order:placed', <?= json_encode($orderData); ?>);
    });
</script>
