<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-carousel';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    ?>
    <ol class="product-items <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item) : ?>
        	<?php
        	   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        	   $product = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
        	   $dataItem = $product->getById($_item->getEntityId());

                $dataDarkMax = $dataItem->getCustomAttribute('dark_circle_score_max') ? 'data-darkCircles-max="'.$dataItem->getCustomAttribute('dark_circle_score_max').'"' : '';
                $dataDarkMin = $dataItem->getCustomAttribute('dark_circle_score_min') ? 'data-darkCircles-min="'.$dataItem->getCustomAttribute('dark_circle_score_min').'"' : '';
                $dataSpotkMax = $dataItem->getCustomAttribute('spot_score_max') ? 'data-ageSpots-max="'.$dataItem->getCustomAttribute('spot_score_max').'"' : '';
                $dataSpotMin = $dataItem->getCustomAttribute('spot_score_min') ? 'data-ageSpots-min="'.$dataItem->getCustomAttribute('spot_score_min').'"' : '';
                $dataWrinkleMax = $dataItem->getCustomAttribute('wrinle_score_max') ? 'data-wrinkles-max="'.$dataItem->getCustomAttribute('wrinle_score_max').'"' : '';
                $dataWrinkleMin = $dataItem->getCustomAttribute('wrinkle_score_min') ? 'data-wrinkles-min="'.$dataItem->getCustomAttribute('wrinkle_score_min').'"' : '';
                $dataTextureMax = $dataItem->getCustomAttribute('texture_score_max') ? 'data-texture-max="'.$dataItem->getCustomAttribute('texture_score_max').'"' : '';
                $dataTextureMin = $dataItem->getCustomAttribute('texture_score_min') ? 'data-texture-min="'.$dataItem->getCustomAttribute('texture_score_min').'"' : '';

        	?>
            <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
            <div class="product-item-info" <?= $dataDarkMax ?> <?= $dataDarkMin ?> <?= $dataSpotkMax ?> <?= $dataSpotMin ?> <?= $dataWrinkleMax ?>  <?= $dataWrinkleMin ?> <?= $dataTextureMax ?> <?= $dataTextureMin ?> >
                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                    <?= $block->getImage($_item, $image)->toHtml() ?>
                </a>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <span class="list_item_product_manufacturer"><?= $_item->getAttributeText("manufacturer"); ?></span>
                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="product-item-link">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>
                    <?php if ($templateType) : ?>
                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <?php endif; ?>

                    <?= $block->getProductPriceHtml($_item, $type) ?>

                    <?= $block->getProductDetailsHtml($_item) ?>

                    <?php if ($showWishlist || $showCompare || $showCart) : ?>
                        <div class="product-item-inner">
                            <div class="product-item-actions">
                                <?php if ($showCart) : ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()) : ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else : ?>
                                            <?php if ($_item->getIsSalable()) : ?>
                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else : ?>
                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($showWishlist || $showCompare) : ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                            <a href="#"
                                               data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                            <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                            <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
        <?php endforeach ?>
    </ol>
<?php endif;?>
