<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View $block */
$_product = $block->getProduct();
$layout = $block->getLayout();
?>

<?php if ($pageBuilder = $_product->getCustomAttribute('product_additional_galery')): ?>
    <?= $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getProductAdditionalGalery(), 'product_additional_galery'); ?>
<?php endif; ?>


