<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $this->helper('Magento\Customer\Helper\Address');
/** @var \WolfSellers\Bopis\Helper\Data $bopisHelper */
$bopisHelper = $this->helper('WolfSellers\Bopis\Helper\Data');
/** @var \WolfSellers\CustomerAddress\Helper\AddressHelper $helper */
$helper = $this->helper('WolfSellers\CustomerAddress\Helper\AddressHelper');
$requiredAttributesPrechecked = $block->getData('required_attributes_prechecked');
?>
<?php $_company = $this->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
<?php
$this->getLayout()
    ->createBlock('Magento\CustomerCustomAttributes\Block\Form',
        "customer_form_address_user_attributes"
    )
    ->setTemplate("WolfSellers_Bopis::address/userattributes.phtml")
    ->setEntityModelClass(\Magento\Customer\Model\Address::class)
    ->setFormCode('customer_address_edit');
$this->getLayout()
    ->createBlock("Magento\CustomerCustomAttributes\Block\Form", "customer_form_template")
    ->setChild("text",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Text" ,"customer_form_template_text")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/text.phtml"))
    ->setChild("textarea",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Textarea" ,"customer_form_template_textarea")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/textarea.phtml"))
    ->setChild("multiline",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Multiline" ,"customer_form_template_multiline")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/multiline.phtml"))
    ->setChild("date",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Date" ,"customer_form_template_date")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/date.phtml"))
    ->setChild("select",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Select" ,"customer_form_template_select")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/select.phtml"))
    ->setChild("multiselect",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Multiselect" ,"customer_form_template_multiselect")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/multiselect.phtml"))
    ->setChild("boolean",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Boolean" ,"customer_form_template_boolean")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/boolean.phtml"))
    ->setChild("file",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\File" ,"customer_form_template_file")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/file.phtml"))
    ->setChild("image",$this->getLayout()->createBlock("Magento\CustomAttributeManagement\Block\Form\Renderer\Image" ,"customer_form_template_image")->setTemplate("Magento_CustomerCustomAttributes::form/renderer/image.phtml"));

?>
<?php $_telephone = $this->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
<?php $_fax = $this->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
<?php $middle = $block->getShowMiddlename(); ?>
<?php $isLoggedIn = $this->getIsLoggedIn(); ?>
<div class="modal-address-form">
<span class="info-title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
<?php if (!$isLoggedIn): ?>
    <span class="address-modal-messages not-logged-in">
            <span>Ingrese a su 
                <a href="<?= $bopisHelper->getLoggedInUrl() ?>">cuenta</a> 
                o abra una <a href="<?= $bopisHelper->getLoggedInUrl() ?>">cuenta nueva</a>.  De lo contrario continue como invitado y llene el formulario. 
            </span>
    </span>

<?php endif; ?>
<form class="form-address" id="form-validate" data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>" autocomplete="off">

    <?= $block->getBlockHtml('formkey') ?>
    <div class="field firstname required">
        <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"><span><?= $block->escapeHtml(__('firstname')) ?></span></label>
        <div class="control">
            <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
                   name="firstname"
                   value=""
                   title="<?= __('firstname') ?>"
                   placeholder="<?= __('firstname') ?>"
                   class="input-text required-entry" <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
        </div>
    </div>
    <?php if ($middle): ?>
        <?php $isMiddlenameRequired = $block->getIsMiddlenameRequired(); ?>
        <div class="field field-name-middlename<?= $isMiddlenameRequired ? ' required' : '' ?>">
            <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('middlename')) ?></span></label>
            <div class="control">
                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"
                       name="<?= $block->escapeHtmlAttr($block->getFieldName('middlename')) ?>"
                       value=""
                       title="<?= $block->escapeHtmlAttr($block->getMiddlenameStoreLabel()) ?>"
                       placeholder="<?= $block->escapeHtmlAttr($block->getMiddlenameStoreLabel()) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($block->getMiddlenameAttributeValidationClass()) ?>" <?= $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
            </div>
        </div>
    <?php endif; ?>
    <div class="field lastname required">
        <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"><span><?= $block->escapeHtml(__('lastname')) ?></span></label>
        <div class="control">
            <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
                   name="lastname"
                   value=""
                   title="<?= __('lastname') ?>"
                   placeholder="<?= __('lastname') ?>"
                   class="input-text required-entry" <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
        </div>
    </div>

    <?php if ($_telephone->isEnabled()): ?>
        <?= $_telephone->toHtml() ?>
    <?php endif ?>

    <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
    <?php if(!$helper->getIsColombia()): ?>
        <div class="field content-street store-base">
            <div class="item-street">
                <div class="control">
                    <input type="text"
                           placeholder="<?= /* @noEscape */ __('Street Address') ?>"
                           name="street[]"
                           value=""
                           title="<?= /* @escapeNotVerified */ __('Street Address') ?>"
                           id="street_1"
                           class="input-text <?= /* @escapeNotVerified */ $_streetValidationClass ?>"/>
                </div>
            </div>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        </div>
    <?php else:?>
        <div class="field content-street store-colombia">
            <div class="item-street">
                <div class="control">
                    <input type="text"
                           name="street[]"
                           value=""
                           title="<?= /* @escapeNotVerified */ __('Street Address') ?>"
                           id="street_1"
                           class="input-text <?= /* @escapeNotVerified */ $_streetValidationClass ?>"/>
                    <span class="pre-street">#</span>
                </div>
            </div>
            <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++): ?>
                <div class="item-street">
                    <div class="control">
                        <input type="text"
                               name="street[]"
                               value=""
                               title="<?= /* @escapeNotVerified */ __('Street Address %1', $_i) ?>" id="street_<?= /* @escapeNotVerified */ $_i ?>"
                               class="input-text <?= /* @escapeNotVerified */ $_streetValidationClass ?>"/>
                        <?php if($_i == 2): ?>
                            <span class="pre-street">-</span>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endfor; ?>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        </div>
    <?endif;?>

    <?php if ($addressHelper->isVatAttributeVisible()) : ?>
        <div class="field taxvat">
            <label class="label" for="vat_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span></label>
            <div class="control">
                <input type="text" name="vat_id" value="" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>" class="input-text <?= /* @escapeNotVerified */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id"/>
            </div>
        </div>
    <?php endif; ?>

    <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_address_user_attributes'); ?>
    <?php if ($userDefinedAttributes):?>
        <?= $userDefinedAttributes->setShowContainer(false)->toHtml() ?>
    <?php endif;?>

    <!--Country-->
    <div class="field country required" style="display: none !important;">
        <div class="control">
            <?= $this->getCountryHtmlSelect() ?>
        </div>
    </div>

    <!--La ciudad será seteada en Model/ResourceModel/Address/Backend/District.php-->
    <div class="field city" style="display:none">
        <div class="control">
            <input type="text" name="city" value="<?= 'Distrito'; ?>" title="<?= 'Distrito' ?>" class="input-text <?= /* @escapeNotVerified */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city"/>
        </div>
    </div>


    <div class="field region required">
        <div class="control">
            <select id="region_id" name="region_id" title="<?= /* @escapeNotVerified */ __('Departamento') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                <option value=""><?= /* @escapeNotVerified */ __('Departamento') ?></option>
            </select>
            <input style="display: none;" type="text" id="region" name="region" value=""  title="<?= /* @escapeNotVerified */ __('Departamento') ?>" class="input-text <?= /* @escapeNotVerified */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
        </div>
    </div>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" class="action submit primary add-address" data-action="add-address"
                    title="<?= /* @escapeNotVerified */ __('Add') ?>">
                <span class="add-address"><?= /* @escapeNotVerified */ __('Add address') ?></span>
            </button>
        </div>
    </div>

</form>

</div>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @escapeNotVerified */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "0",
                "countriesWithOptionalZip": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        },
        "#region_id": {
            "provinceUpdater": {
                "optionalRegionAllowed": <?= /* @escapeNotVerified */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#province_id",
                "regionInputId": "#province",
                "currentRegion": "0",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @escapeNotVerified */ $this->helper('Omnipro\CustomerAddress\Helper\Data')->getProvinceJson() ?>,
                "defaultRegion": "0",
                "countriesWithOptionalZip": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        },
        "#province_id": {
            "districtUpdater": {
                "optionalRegionAllowed": <?= /* @escapeNotVerified */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#district_id",
                "regionInputId": "#district",
                "currentRegion": "0",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @escapeNotVerified */ $this->helper('Omnipro\CustomerAddress\Helper\Data')->getDistrictJson() ?>,
                "defaultRegion": "0",
                "countriesWithOptionalZip": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script>
    require([
        "jquery",
        "mage/mage",
        'mage/validation'
    ], function($){
        $('#form-validate').mage('validation', {
            errorPlacement: function(error, element) {
                if (element.is('#street_1') || element.is('#street_2') || element.is('#street_3')) {
                    error.appendTo('.content-street');
                } else {
                    element.after(error);
                }
            },
            messages: {
                'identificacion': {
                    'validate-length': 'Ingrese entre 6 y 10 dígitos.'
                },
                'telephone': {
                    'validate-length': 'Ingrese entre 6 y 9 dígitos.'
                }
            }
        });
        $("#identificacion").keypress(function(e){
            var pressed = String.fromCharCode(e.which);
            if (!pressed.match(/^[0-9]+$/)) {
                e.preventDefault();
            }
        });
        $("#telephone").removeClass('maximum-length-10');
        $("#telephone").addClass('maximum-length-9');
        $("#identificacion, #firstname, #lastname, #street_1, #telephone").keyup(function(){
            $.validator.validateSingleElement(this);
        });
    });
</script>
