<?php
/** @var $block \WolfSellers\Bopis\Block\Address\Grid */
?>
<?php $addresses = $this->getAddresses(); ?>
<div class="modal-addresses-grid">
    <span class="info-title"><?= $block->escapeHtml(__('Shipping Address')); ?></span>
    <?php if (count($addresses) > 0): ?>
        <?php foreach ($addresses as $address): ?>
    <div class="address-item">
        <input type="radio" id="address-<?= $address->getId(); ?>" name="address_id" value="<?= $address->getId(); ?>" />
        <label for="address-<?= $address->getId(); ?>"><?= $block->escapeHtml($block->getStreetAddress($address)) ?></label>
        <div class="address-data">
            <div class='direccion'>
            </div>
            <div class='ciudad'><?= $block->escapeHtml($address->getCity()) ?></div>
            <div class='pais'><?= /* @escapeNotVerified */ $block->getCountryByCode($address->getCountryId()) ?></div>
            <div class='estado'><?= /* @escapeNotVerified */ $address->getRegion() ?></div>
            <div class='telefono'><?= $block->escapeHtml($address->getTelephone()) ?></div>
        </div>
    </div>
        <?php endforeach; ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" class="action submit primary select-address"
                    title="<?= /* @escapeNotVerified */ __('Select') ?>">
                <span class="select-address"><?= /* @escapeNotVerified */ __('Select') ?></span>
            </button>
        </div>
        <div class="primary">
            <button type="button" class="action submit primary add-another-address"
                    title="<?= /* @escapeNotVerified */ __('Add another address') ?>">
                <span class="add-another-address"><?= /* @escapeNotVerified */ __('Add another address') ?></span>
            </button>
        </div>
    </div>
    <?php endif; ?>
</div>
