<?php
$address = $this->getAddress();
?>

<div class="modal-addresses-grid">
    <span class="info-title"><?= $block->escapeHtml(__('Shipping Address')); ?></span>
    <br>
    <div>
        <div class="field selected-address">
            <div class="control">
                <div class="address-data">
                    <div class='direccion'>
                        <?php for ($i = 1 ; $i < sizeof($address) ; $i++ ):?>
                        <?= $block->escapeHtml($address['street_' . $i] ?? "") ?>
                        <?php endfor;?>
                    </div>
                    <div class='ciudad'><?= $block->escapeHtml($address['province']) ?></div>
                    <div class='pais'><?= /* @escapeNotVerified */ $address['country'] ?></div>
                    <div class='estado'><?= /* @escapeNotVerified */ $address['region'] ?></div>
                </div>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="button" class="action submit primary add-another-address" data-action="add-another-address"
                        title="<?= /* @escapeNotVerified */ __('Add another address') ?>">
                    <span class="add-another-address"><?= /* @escapeNotVerified */ __('Add another address') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
