<?php
/**
 * @copyright Copyright (c) 2024 Vass
 * @package Vass_Wishlist
 * @author Vass Team
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()) : ?>
    <a class="action edit" href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>">
        <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
