<?php
/**
 * @copyright Copyright (c) 2024 Vass
 * @package Vass_Wishlist
 * @author Vass Team
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */
?>

<a href="#" data-role="remove" data-post-remove='<?= /* @noEscape */ $block->getItemRemoveParams($block->getItem()) ?>' title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete">
    <span><?= $block->escapeHtml(__('Remove item')) ?></span>
</a>
