<?php
/** @var \Amasty\MegaMenuLite\Block\Container $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\MegaMenuLite\ViewModel\Store\Menu $viewModel
 */

$viewModel = $block->getViewModel();
?>
<section class="ammenu-menu-wrapper"
         data-bind="
            scope: 'ammenu_wrapper',
            mageInit: {
                'Magento_Ui/js/core/app': {
                    components: {
                        'ammenu_wrapper': {
                            component: 'Amasty_MegaMenuLite/js/wrapper',
                            data: <?= $escaper->escapeHtml($block->getJsData()) ?>,
                            config: <?= $escaper->escapeHtml($block->getSerializedJsConfig()) ?>,
                            children: <?= $escaper->escapeHtml($block->getJsComponents()) ?>,
                            settings: <?= $escaper->escapeHtml($block->getJsSettings()) ?>,
                            links: <?= $escaper->escapeHtml($block->getStoreLinks()) ?>,
                            isMobile: <?= (int) true ?>
                        }
                    }
                }
            }">

    <?php if (method_exists($viewModel, "isMobile")): ?>
    <?php if (!$viewModel->isMobile()): ?>
        <div class="megamenu_desk">
        <?= $block->getChildBlock('ammenu.top.menu')->setItems($block->getAllNodesData())->toHtml() ?>
        </div>
    <?php endif; ?>
    <div class="megamenu_mobile">
    <?php if ($viewModel->isHamburger() && $viewModel->isMobile()): ?>
        <!-- ko scope: 'index = ammenu_sidebar_menu_wrapper' -->
            <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- /ko -->
        <!-- ko scope: 'index = ammenu_overlay_wrapper' -->
            <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- /ko -->
    <?php endif; ?>
    </div>
    <?php else: ?>
    
        <div class="megamenu_desk">
        <?= $block->getChildBlock('ammenu.top.menu')->setItems($block->getAllNodesData())->toHtml() ?>
        </div>
    <?php endif; ?>
</section>


<script type="text/x-magento-init">
    {
        "*": {
            "Amasty_MegaMenuLite/js/responsive" : {
            }
        }
    }
</script>
