<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($item = $block->getItem()) : ?>

    <?php if ($item->getAppliedRuleIds()) : ?>
        <span><?= round($item->getDiscountPercent(), 1) ?>%</span>
    <?php else: ?>
        <span><?= 100-round(100*$item->getPrice()/$item->getBaseOriginalPrice(),1) ?>%</span>
    <?php endif; ?>
<?php endif; ?>
