<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \WolfSellers\Bopis\Block\Adminhtml\Order\View\Items\Totals $block */

?>
<?php if ($item = $block->getItem()) : ?>
    <table class="subtotales-bopis">
        <tr>
            <td style="vertical-align: middle;">
                <?=
                $item->getOrder()->formatPricePrecision($item->getBaseRowTotalInclTax(), 2, false); ?>
            </td>
        </tr>
    </table>
<?php endif; ?>
