<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
/** @var \Magento\Cookie\Helper\Cookie $cookieHelper */
$cookieHelper = $block->getData('cookieHelper');
if ($cookieHelper->isCookieRestrictionModeEnabled()): ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block">
        <div role="document" class="content" tabindex="0">
            <div class="container-button-close">
                <button class="close-button ot-close-icon" aria-label="Cerrar"></button>
            </div>
            <h3 class="cookies-title">
                <?= $block->escapeHtml(__('Informative note')) ?>
            </h3>
            <div class="cookies-text">
                <span>
                    <?= $block->escapeHtml(__('We and selected third parties use cookies or similar technologies for technical purposes and, with your consent, for other purposes as specified in the')) ?>
                    <?= $block->escapeHtml(__('<a href="%1">cookie policy</a>.', $block->getPrivacyPolicyLink()), ['a']) ?>
                </span>
                <p>
                    <?= $block->escapeHtml(__('You can consent to the use of such technologies by using the "Accept" button. By closing this informative note, you continue without accepting.')) ?>
                </p>
            </div>
            <div class="actions">
                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('Accept cookies')) ?></span>
                </button>
            </div>
        </div>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#notice-cookie-block') ?>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->getUrl('cookie/index/noCookies')) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
