<?php
    /** @var $block \WolfSellers\OrderQR\Block\Onepage\Success */
?>

<?php if($block->getIsPickup()): ?>
    <div class="qrWrap">
        <div class="qrOrderNumber">Orden No: <a href="<?= $block->getViewOrderUrl() ?>"><?= $block->getOrderId() ?></a></div>
        <p class="qrOrderInformation">
            <?= sprintf(__("Se enviará un mensaje con <b>toda la información de tu pedido</b> por correo electrónico y podrás recogerlo a partir del día <b>%s</b> en un rango de 8am a 9:30pm"),$block->getDeliveryDate())?>
        </p>
        <div class="qr-container">
            <div class="qr-code"><img src="<?= $block->getQrImage() ?>" alt="qr-code"></div>
            <div class="qr-description">
                <?= __("Deberás mostrar este código QR junto con tu documento de identidad para poder retirar tu pedido en tienda."); ?>
                <a href="https://api.whatsapp.com/send?text=<?= $block->getQrImage() ?>" data-action="share/whatsapp/share" target="_blank">
                    <div class="qr-share-whatsapp">
                        <?=__("Share by Whatsapp") ?>
                    </div>
                </a>
            </div>
        </div>
        <div class="remember">
            <span class="iconAlert"></span>
            <?= __("Recuerda que tienes hasta 7 días posteriores para recoger tus productos, de lo contrario tu compra será anulada y se procederá a la devolucion del dinero.") ?>
        </div>
        <a class="back-to-store" href="/"><?= __("Regresar a la tienda"); ?></a>
    </div>
<?php endif; ?>
