# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.4
    disk: 10240

redis:
    type: redis:6.2

rabbitmq:
    type: rabbitmq:3.9
    disk: 1024
