<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \WolfSellers\Bopis\Block\Adminhtml\Order\View\Tab\Info */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$btnAvailable = $block->isBtnMetodoPagoAvailable();

?>
<?php $_order = $block->getOrder() ?>

<div id="order-messages">
    <?= $block->getChildHtml('order_messages') ?>
</div>

<?= $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= (int) $_order->getId() ?>"/>

<section class="admin__page-section bopis-data card-payment">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item bopis-payment-method">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title icon-tarjeta">
                <span class="title"><?= $block->escapeHtml(__('Método de pago')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <span class="color-orange"><?= $_order->getPayment()->getMethodInstance()->getTitle(); ?></span><br />
                <?= $block->getPaymentHtml() ?>
                <?php if($_order->getPayment()->getMethod() == 'tilopay_fac'):?>
                    <?= $block->getTiloData(); ?>
                <?php endif;?>
                <br>
                <span>No de tarjeta: <?=$_order->getPayment()->getCcLast4() ? '****' . $_order->getPayment()->getCcLast4() : '' ?></span> <br>
                <span>Nombre: <?=$_order->getBillingAddress()->getFirstname() . $_order->getBillingAddress()->getLastname()?></span>
            </div>
            <?php if ($block->getAdminUserType() == 1):?>
            <button name="btn-confirmacion-cliente-metodo-pago"
                    value="Detener"
                    class="btn-confirmacion-cliente btn-confirmacion-cliente-metodo-pago <?= $this->getOrder()->getData("verificacion_bopis_metodo_pago") > 0 ? "":"confirmado" ?>"
                <?= $btnAvailable ? "":'disabled="disabled"' ?>
                    data-order-id="<?= $_order->getEntityId() ?>"
                    data-type="4"
            >
                <?= $this->getOrder()->getData("verificacion_bopis_metodo_pago") > 0 ? "CONFIRMADO":"CONFIRMAR" ?>
            </button>
             <?php endif;?>
        </div>
    </div>
</section>

<section class="admin__page-section">
    <?= $block->getItemsHtml() ?>
</section>


<?= $block->getChildHtml('popup_window') ?>
<style>
    .bopis-data {
        width: calc(25% - 15px);
        display: inline-flex;
    }
</style>
