<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\GoogleTagManager\Block\Ga $block */

$accountType = $block->getConfig(\Magento\GoogleTagManager\Helper\Data::XML_PATH_TYPE);
$gtmAccountId = $block->getConfig(\Magento\GoogleTagManager\Helper\Data::XML_PATH_CONTAINER_ID);
$gapAccountId = $block->getConfig(\Magento\GoogleTagManager\Helper\Data::XML_PATH_ACCOUNT);
$_product = $block->getProductBlock();
$gender = '';
$size = '';

if (!empty($_product)) {
    $category = !empty($_product->getData('categoria')) ? $_product->getData('categoria') : '';
    $subcategory = !empty($_product->getData('sub_categoria')) ? $_product->getData('sub_categoria') : '';
    $family = !empty($_product->getData('familia')) ? $_product->getData('familia') : '';

    $attr = $_product->getResource()->getAttribute('tamano');

    if ($attr->usesSource()) {

        $size = $attr->getSource()->getOptionText($_product->getTamano());
    }

    $attr = $_product->getResource()->getAttribute('genero');

    if ($attr->usesSource()) {

        $gender = $attr->getSource()->getOptionText($_product->getGenero());
    }

    $attributes = $_product->getAttributes();
    $brand = '';

    foreach($attributes as $attribute){

        if($attribute->getName() === 'manufacturer') {
            $brand = $attribute->getFrontend()->getValue($_product);
        }
    }

    $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
        ->init($_product, 'product_base_image')->getUrl();

    $rules = $block->getRules($_product->getId());

    $data = [];

    if($rules){

        foreach ($rules as $rule){

            $data[] = $rule;
        }
    }

    $data = implode( ', ', $data);
}


 switch ($accountType) {
    case \Magento\GoogleTagManager\Helper\Data::TYPE_TAG_MANAGER:
        if (!empty($gtmAccountId)) {
            ?>
            <!-- GOOGLE TAG MANAGER -->
            <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_GoogleTagManager/js/google-tag-manager": {
                        "isCookieRestrictionModeEnabled": <?= (int)$block->isCookieRestrictionModeEnabled() ?>,
                        "currentWebsite": <?= (int)$block->getCurrentWebsiteId() ?>,
                        "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                        "gtmAccountId": "<?= $block->escapeJs($gtmAccountId) ?>",
                        "storeCurrencyCode": "<?= $block->escapeJs($block->getStoreCurrencyCode()) ?>",
                        "ordersData": <?= /* @noEscape */ json_encode($block->getOrdersDataArray()) ?>
                    }
                }
            }
            </script>
            <!-- END GOOGLE TAG MANAGER -->
            <?php
        }
        break;
    case \Magento\GoogleTagManager\Helper\Data::TYPE_UNIVERSAL:
        if (!empty($gapAccountId)) {
            ?>
            <!-- BEGIN GOOGLE UNIVERSAL ANALYTICS CODE -->
            <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_GoogleAnalytics/js/google-analytics": {
                        "isCookieRestrictionModeEnabled": <?= (int)$block->isCookieRestrictionModeEnabled() ?>,
                        "currentWebsite": <?= (int)$block->getCurrentWebsiteId() ?>,
                        "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                        "ordersTrackingData": <?= /* @noEscape */ json_encode($block->getOrdersTrackingData()) ?>,
                        "pageTrackingData": <?= /* @noEscape */ json_encode($block->getPageTrackingData($gapAccountId)) ?>
                    }
                }
            }
            </script>
            <!-- END GOOGLE UNIVERSAL ANALYTICS CODE -->
            <?php
        }
        break;


}


if (!empty($_product)) {
    ?>
    <!-- GOOGLE TAG MANAGER - CUSTOM WOLF SELLERS (item_view)-->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_GoogleTagManager/js/actions/product-detail": {
                    "product":{
                        "id": "<?= $_product->getId() ?>",
                        "totalValue": "<?= $_product->getFinalPrice() ?>",
                        "name": "<?= $_product->getName() ?>",
                        "sku": "<?= $_product->getSku() ?>",
                        "category": "<?= $category ?>",
                        "sub_categoria": "<?= $subcategory ?>",
                        "familia": "<?= $family ?>",
                        "brand": "<?= $brand ?>",
                        "productURL": "<?= $_product->getProductUrl() ?>",
                        "imageURL": "<?= $imageUrl ?>",
                        "genero": "<?= $gender ?>",
                        "tamano": "<?= $size ?>",
                        "promotion": "<?= $data ?>"
                    },
                    "currencyCode": "<?=$block->getCurrencyCode();?>"
                }
            }
        }
    </script>
    <!-- END GOOGLE TAG MANAGER -->
    <?php
}
