<?php
/** @var \WolfSellers\Bopis\Helper\Config $bopisHelper */
$bopisHelper = $this->helper('WolfSellers\Bopis\Helper\Config');
?>
<?php if($bopisHelper->isActive()):?>
<div class="selected-address" data-bind="scope:'bopis' ">
    <!-- ko if:isVisible -->
    <p data-bind="attr:{class:bopis().type}, text: bopis().type == 'delivery' ? 'Envío a domicilio' : 'Tienda seleccionada'"></p>
    <!-- ko if: bopis().type == 'store-pickup' -->
        <span class="store-pickup" data-bind="html: bopis().formatted"></span>
        <a class="select-source" href="javascript:void(0)">Cambiar tienda</a>
    <!-- /ko -->
    <!-- ko if: bopis().type == 'delivery' -->
        <span class="delivery">Envío a domicilio</span>
        <!-- <a class="shipping-address" href="javascript:void(0)">Ingresar dirección de envío</a> -->
    <!-- /ko -->
    <div class="bopis-modal" style="display: none;"></div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "bopis": {
                    "component": "WolfSellers_Bopis/js/section",
                    "isVisible": "<?=$block->isVisible()?>"
                }
            }
        },
        "WolfSellers_Bopis/js/shipping-type": {}
    }
}
</script>
<?php endif; ?>
