<div id="minicart-proceed-confirmation-popup-content" style="display: none;">
    <div class="custom-popup-content">
        <p>
            Actualmente tienes uno o más productos en tu carrito que no cuenta con el método de entrega "<b>Envío
                rápido </b>", edita tu carrito y guarda para después tus productos o realiza tu pedido completo con
            "<b>Envío Regular o Retiro en tienda</b>"
        </p>

        <p>
            <span class="tag"> <span class="icon-method-regular"></span> <?= __('ENVÍO REGULAR') ?> </span>
            <span class="available"> <span class="icon-check"></span> Disponible</span>
            <span class="wait-time"><?= __('Llega de 2 a 3 días.') ?></span>
        </p>
        <p>
            <span class="tag"> <span class="icon-method-instore"></span> <?= __('Retiro en tienda') ?> </span>
            <span class="available"> <span class="icon-check"></span> Disponible</span>
            <span class="wait-time"><?= __('Puedes recogerlo después de 1 o 2 días.') ?></span>
        </p>

        <p>
            Si requiere su entrega con "<b>Envío rápido</b>" le sugerimos realizar su compra en dos pedidos.
        </p>
    </div>
</div>
