<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 * @var \Magento\Framework\Escaper $escaper
 */

$item = $block->getData('item');
$isIconsAvailable = $block->getData('isIconsAvailable');
$hasContent = isset($item['content'])? 'ammenu-content-hasitems' : '';

/** @var $viewModel \WolfSellers\Menu\ViewModel\ItemMenu */
$viewModel = $block->getViewModel();
$cssClass = $viewModel->getCssClass($item);
?>

<a if="item.isVisible"
   class="ammenu-link <?= $hasContent.' '.$cssClass ?>"
   style="font-weight: <?= $escaper->escapeHtmlAttr($item['desktop_font'] ?? '') ?>"
   data-bind="
        event: {
            mouseenter: onMouseenter,
            mouseleave: onMouseleave
        },
        style: {
            'color': item.color() ? item.color() : '',
            'background': item.backgroundColor() ? item.backgroundColor() : ''
        },
        attr: { href: item.url ? item.url : '#' },
        css: { '-current': item.current }" id="<?= $item["id"] ?>">
    <?php if ($isIconsAvailable): ?>
        <?= /* @noEscape */ $block->getChildBlock('ammenu.top.menu.icon')->setData('item', $item)->toHtml() ?>
    <?php endif; ?>

    <p class="ammenu-text-block" data-mage-init='{"Magento_Theme/js/hover-menu-tabs": {}}'>
        <span class="ammenu-text"><?= $escaper->escapeHtml($item['name']) ?></span>
        <?php if (isset($item['label'])): ?>
            <span class="ammenu-label"
                  style="
                      background: <?= $escaper->escapeHtmlAttr($item['label']['label_background_color'] ?? '') ?>;
                      color: <?= $escaper->escapeHtmlAttr($item['label']['label_text_color'] ?? '') ?>;">
                <?= $escaper->escapeHtml($item['label']['label'] ?? '') ?>
            </span>
        <?php endif; ?>
    </p>
</a>
