<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <div class="control">
        <select id="sorter" data-role="sorter" class="sorter-options">
            <option disabled selected value="">
                <?= $block->escapeHtml(__('Sort By')) ?>
            </option>
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>">
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
